name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3 # Checks out the repository using the already built github.com/actions/checkout action
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3 # Installs and prepares python3 env on the build image
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip # Runs the commands for installing pip and the project the dependencies
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test # Launches the unit tests through the django manage.
